Support for transforming a Nadel instance
atlassian-labs/nadel pull request #240
Opened 2021-05-03 05:05 UTC by bbakerman

I chose o make this Transformer class like a builder but not the builder.

This will allow future expansion of the things that can be transformed

2021-05-03 05:49 UTC, temaEmelyan approved these changes

2021-05-03 05:50 UTC, andimarek requested changes
I don't thinks this is the right way as this bypasses a lot of init code. The new engine also relies on the overall schema. Not sure what happens if we change it.

2021-05-03 10:00 UTC, andimarek requested changes
small thing around asserts

2021-05-04 00:59 UTC, bbakerman commented on api/src/main/java/graphql/nadel/Nadel.java
> +            Objects.requireNonNull(executionEngine, "The engine factory must return an engine instance");
done

2021-05-04 01:06 UTC, bbakerman reviewed
done

2021-05-04 01:07 UTC, merged