Handle errors in dynamic service resolution
atlassian-labs/nadel pull request #261
Opened 2021-06-11 04:13 UTC by felipe-gdr

Introduces better error handling in the dynamic service resolution process.

Consumers should avoid throwing exceptions in the service resolution hook, and instead return GraphQL errors with helpful messages and metadata.

The Nadel engine will bypass normal execution for the root node which caused the error and instead craft a result node containing the error message and other details about the field.

2021-06-11 04:15 UTC, felipe-gdr commented on engine/src/test/groovy/graphql/nadel/e2e/NadelE2ETest.groovy
> -
Split the tests into their own class to keep things more organised

2021-06-11 04:15 UTC, felipe-gdr commented on api/src/main/java/graphql/nadel/hooks/ServiceExecutionHooks.java
> +    default ServiceOrError resolveServiceForField(List<Service> services, ExecutionStepInfo executionStepInfo) {
Getting a `ExecutionStepInfo` which contains everything the hook method will need to create a `GraphQLError`.

2021-06-11 04:33 UTC, andimarek requested changes

2021-06-11 04:33 UTC, andimarek commented on engine/src/test/groovy/graphql/nadel/e2e/NadelE2EDynamicServiceResolutionTest.groovy
> +import graphql.nadel.*
can you change your formatter to never use * imports? Have a look at the GraphQL formatter in the GJ repo.

2021-06-11 04:33 UTC, andimarek commented on engine/src/test/groovy/graphql/nadel/e2e/NadelE2EDynamicServiceResolutionTest.groovy
> +class NadelE2EDynamicServiceResolutionTest extends StrategyTestHelper {
We should add at least on GraphQLE2ETest and not only StrategyTests.

2021-06-11 04:33 UTC, andimarek commented on engine/src/test/groovy/graphql/nadel/e2e/NadelE2EDynamicServiceResolutionTest.groovy
> +                    new GraphQLError() {
we have a GraphQLErrorBuilder in GJ which helps you to create errors.

2021-06-15 00:24 UTC, felipe-gdr commented on engine/src/test/groovy/graphql/nadel/e2e/NadelE2ETest.groovy
> -    def '''bugfix: check that a field that is used as an input for a hydration is not dropped from the response if it's
Moved this test to the Strategy test class

2021-06-16 23:40 UTC, andimarek approved these changes
Great work!

2021-06-16 23:42 UTC, merged