aemelyanenko: bug fix hydration within hydration with variables
atlassian-labs/nadel pull request #280
Opened 2021-07-09 02:21 UTC by temaEmelyan

wip for the bugfix

2021-07-11 23:46 UTC, gnawf commented on test/src/test/resources/fixtures/replicate-bug.yml
> +  #language=graphQL
Idk about you, but this turns out really bad for me. You always get syntax errors saying you redefined a field or something rather

2021-07-12 04:02 UTC, andimarek commented on test/src/test/resources/fixtures/hydration-within-hydration-with-variables.yml
> +  "id": "some-id",
remove that variable if not used/

2021-07-12 04:06 UTC, andimarek requested changes
see comment

2021-07-12 05:11 UTC, temaEmelyan commented on test/src/test/resources/fixtures/hydration-within-hydration-with-variables.yml
> +  "id": "some-id",
done

2021-07-12 05:12 UTC, andimarek approved these changes

2021-07-12 05:42 UTC, merged