support for @hidden directive
atlassian-labs/nadel pull request #360
Opened 2022-01-18 02:03 UTC by temaEmelyan

Please make sure you consider the following:

- [ ] Add tests that use __typename in queries
- [ ] Does this change work with all nadel transformations (rename, type rename, hydration, etc)? Add tests for this.
- [ ] Is it worth using hints for this change in order to be able to enable a percentage rollout?
- [ ] Do we need to add integration tests for this change in the graphql gateway?
- [ ] Do we need a pollinator check for this?

2022-01-18 02:06 UTC, bbakerman commented on api/src/main/java/graphql/nadel/Nadel.java
> +    final GraphQLSchema privateOverallSchema;
naming matters - its not private - LTE NOT NOT use this

Its meant to be the schema for "querying" and "introspection"

2022-01-18 02:07 UTC, temaEmelyan commented on api/src/main/java/graphql/nadel/Nadel.java
> +    final GraphQLSchema privateOverallSchema;
I think we can extend  `NadelPublicGraphQLSchema` and `NadelPrivateGraphQLSchema` for better type safety (they can either extend GraphQLSchema or wrap it)

2022-01-18 02:14 UTC, bbakerman commented on api/src/main/java/graphql/nadel/schema/PublicSchemaGenerator.java
> +public class PublicSchemaGenerator {
Not public - not private

QuerySchema and OverallSchema

2022-01-18 02:14 UTC, bbakerman commented on engine-nextgen/src/main/kotlin/graphql/nadel/enginekt/blueprint/NadelExecutionBlueprint.kt
> +    val privateSchema: GraphQLSchema,
querySchema and overallSchema

2022-01-18 02:55 UTC, bbakerman commented on api/src/main/java/graphql/nadel/schema/NadelDirectives.java
> +                .description(createDescription("Indicates that the field is not available for queries"))
Indicates that the field is not available for queries or introspection

2022-01-18 02:55 UTC, bbakerman commented on api/src/main/java/graphql/nadel/schema/PublicSchemaGenerator.java
> +public class PublicSchemaGenerator {
naming discussed online

2022-01-19 22:36 UTC, gnawf requested changes
Some comments about usage of `engineSchema` vs `querySchema`. Also a couple more tests would be great.

Happy to approve after :)

2022-01-19 22:36 UTC, gnawf commented on test/src/test/resources/fixtures/hidden/can-query-non-hidden-fields.yml
> +name: can query non hidden fields
Unrelated to this diff, but can we add another test for `@hidden` fields not at the top level?

Only thing I'd be worried about testing there is that the top level field routing is somehow being the one handling the hidden fields, then nested fields are never checked.

e.g. we should have a test like

```
type Query {
  hello: World
}

type World {
  area51: Area @hidden
}
```

where the query is

```
{
  hello {
    area51
  }
}
```

2022-01-19 22:36 UTC, gnawf commented on test/src/test/resources/fixtures/hidden/introspection-does-not-show-hidden-fields.yml
> +      hiddenField: String @hidden
Nit: can we sprinkle a few more hidden fields on some other types?

2022-01-19 22:36 UTC, gnawf commented on api/src/main/java/graphql/nadel/Nadel.java
> +        NadelInstrumentationQueryExecutionParameters instrumentationParameters = new NadelInstrumentationQueryExecutionParameters(executionInput, querySchema, instrumentationState);
Hmmm, wondering whether it's correct to pass in engine or query schema here. I'm leaning towards engine schema, but I see that this is also before any validation has occurred… hmmm.

2022-01-19 22:36 UTC, gnawf commented on engine-nextgen/src/main/kotlin/graphql/nadel/enginekt/transform/query/NadelFieldToService.kt
> +        return isNamespacedField(field, querySchema)
I think we should swap this back to engine schema. If we stick to the rule that

1. Query schema for anything user facing (validation, introspection).
2. Engine schema for almost everything else.

It's a lot easier to understand what to use. We should add a comment about that on `querySchema` somewhere too.

2022-02-01 01:03 UTC, gnawf approved these changes
Nice

2022-02-09 22:12 UTC, merged