Adding conditional hydration validation
atlassian-labs/nadel pull request #477
Opened 2023-12-05 03:52 UTC by sbarker2

Please make sure you consider the following:

- [ ] Add tests that use __typename in queries
- [ ] Does this change work with all nadel transformations (rename, type rename, hydration, etc)? Add tests for this.
- [ ] Is it worth using hints for this change in order to be able to enable a percentage rollout?
- [ ] Do we need to add integration tests for this change in the graphql gateway?
- [ ] Do we need a pollinator check for this?

2023-12-05 23:05 UTC, gnawf requested changes
Some changes, but should be good to go after.

2023-12-07 02:55 UTC, gnawf requested changes

2023-12-07 02:55 UTC, gnawf commented on lib/src/main/java/graphql/nadel/validation/NadelHydrationWhenConditionValidation.kt
> +        if (whenConditionSourceField.type !is GraphQLScalarType){
This would fail if the field type is non-nullable.

We need to let fields be non-nullable.

2023-12-07 02:55 UTC, gnawf commented on lib/src/main/java/graphql/nadel/validation/NadelHydrationWhenConditionValidation.kt
> +            return return NadelSchemaValidationError.WhenConditionUnsupportedFieldType(whenConditionSourceFieldName, "", overallField)
Did you leave the type name here blank on purpose?

You should be able to get a type name using something like `GraphQLTypeUtil.simplePrint(whenConditionSourceField.type)`

2023-12-11 23:21 UTC, sbarker2 commented on lib/src/main/java/graphql/nadel/validation/NadelHydrationWhenConditionValidation.kt
> +        val whenConditionSourceField = (parent.overall as GraphQLFieldsContainer).getField(whenConditionSourceFieldName)
isn't that just every other hydration test?

2023-12-12 02:26 UTC, gnawf approved these changes

2023-12-12 02:34 UTC, merged